import Head from 'next/head'
import { Channel } from '@/components/Channel'


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 h-full">
        <div className="flex justify-center gap-2 p-4 bg-gray-900 h-full">
          <Channel/>
        </div>
      </main>
    </>
  )
}
