import Head from 'next/head'
import { Country } from '@/components/Country'
import { Channel } from '@/components/Channel'
import { useState } from 'react'
import { Stream } from '@/components/Stream'

export default function Home() {
  const [country, setCountry] = useState('BR')
  const [channel, setChannel] = useState('BR')

  function handleChangeCountry(countryCode: string) {
    setCountry(countryCode)
  }

  function handleChangeChannel(channelId: string) {
    setChannel(channelId)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex gap-2 p-4 bg-gray-900 h-full">
        <Country countryCode={country} onChangeCountry={handleChangeCountry}/>
        <Channel countryCode={country} channelId={channel} onChangeChannel={handleChangeChannel}/>
        <Stream channelId={channel} /> 
      </main>
    </>
  )
}
